# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\AhJayzZ\Desktop\NTUST\Project\SideProject\EscapeFromNinja\UI\Ui_files\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1500, 800)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainCharacterLabel = QtWidgets.QLabel(self.centralwidget)
        self.mainCharacterLabel.setGeometry(QtCore.QRect(380, 340, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.mainCharacterLabel.setFont(font)
        self.mainCharacterLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mainCharacterLabel.setObjectName("mainCharacterLabel")
        self.healthBar = QtWidgets.QProgressBar(self.centralwidget)
        self.healthBar.setGeometry(QtCore.QRect(10, 10, 181, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.healthBar.setFont(font)
        self.healthBar.setStyleSheet("color:red")
        self.healthBar.setProperty("value", 100)
        self.healthBar.setObjectName("healthBar")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1500, 25))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.mainCharacterLabel.setText(_translate("mainWindow", "Main"))
